FROM alpine:3.15

ENV TZ=Europe/Rome

# ------------------------------------------------------------------------------------------------------------------- #
# Dependencies
# ------------------------------------------------------------------------------------------------------------------- #
RUN apk --update --no-cache add \
  php7 \
  php7-fpm \
  php7-common \
  php7-ctype \
  php7-curl \
  php7-fileinfo \
  php7-mbstring \
  php7-zip \
  php7-dom \
  php7-json \
  php7-xml \
  php7-phar \
  php7-tokenizer \
  php7-openssl \
  php7-iconv \
  php7-opcache \
  php7-pdo_mysql \
  php7-gd \
  php7-soap \
  php7-session \
  php7-sodium \
  php7-sockets \
  php7-pdo \
  php7-intl \
  php7-bcmath \
  php7-xsl \
  php7-xmlwriter \
  php7-exif \
  php7-simplexml \
  php7-xdebug \
  wget \
  curl \
  git \
  supervisor \
  nginx \
  tzdata \
  openssl \
  mysql-client \
  && \
  ln -s /usr/sbin/php-fpm7 /usr/sbin/php-fpm \
  && \
  ln -s /etc/php7 /etc/php
# ------------------------------------------------------------------------------------------------------------------- #

# ------------------------------------------------------------------------------------------------------------------- #
# Install Composer
# ------------------------------------------------------------------------------------------------------------------- #
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer \
  && rm -rf /var/www && mkdir -p /var/www \
  && cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
  && rm -rf /var/cache/apk/* /root/.composer/cache/*
# ------------------------------------------------------------------------------------------------------------------- #

# ------------------------------------------------------------------------------------------------------------------- #
# Install Drush CLI
# ------------------------------------------------------------------------------------------------------------------- #
RUN wget -O drush.phar https://github.com/drush-ops/drush-launcher/releases/latest/download/drush.phar \
  && chmod u+x drush.phar \
  && mv drush.phar /usr/local/bin/drush \
  && echo 'alias drush="drush --root=/var/www"' | tee ~/.profile \
  && source ~/.profile
# ------------------------------------------------------------------------------------------------------------------- #

# ------------------------------------------------------------------------------------------------------------------- #
# Install Drupal CLI
# ------------------------------------------------------------------------------------------------------------------- #
#RUN curl https://drupalconsole.com/installer -L -o drupal.phar \
#  && chmod u+x drupal.phar \
#  && mv drupal.phar /user/local/bin/drupal
# ------------------------------------------------------------------------------------------------------------------- #

# ------------------------------------------------------------------------------------------------------------------- #
# fix work iconv library with alphine
# ------------------------------------------------------------------------------------------------------------------- #
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
# ------------------------------------------------------------------------------------------------------------------- #

# ------------------------------------------------------------------------------------------------------------------- #
# Configurations
# ------------------------------------------------------------------------------------------------------------------- #
COPY nginx.conf /etc/nginx/nginx.conf
COPY php.ini /etc/php/php.ini
COPY php-fpm.conf /etc/php/php-fpm.conf
COPY supervisord.conf /etc/supervisord.conf
# ------------------------------------------------------------------------------------------------------------------- #

WORKDIR /var/www

EXPOSE 80

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
